name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-on-mac:
    strategy:
      matrix:
        runs-on: [macos-11.0, macos-10.15]
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v2
    - name: brew install
      run: brew install meson gettext gtk+3 jsoncpp glog
    - name: meson
      run: meson builddir
    - name: build
      run: ninja -v -C builddir
    - name: test
      run: ninja -v -C builddir test
    - name: install
      run: ninja -C builddir install

  build-on-linux:
    strategy:
      matrix:
        runs-on: [ubuntu-18.04, ubuntu-20.04]
        compiler: [g++, clang++]
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v2
    - name: apt install
      run: sudo apt install -y libgoogle-glog-dev libgtk-3-dev libglib2.0-dev libgstreamer1.0-dev libjsoncpp-dev g++ meson xvfb
    - name: meson
      run: meson builddir
      env:
        CXX: ${{ matrix.compiler }}
    - name: build
      run: ninja -v -C builddir
    - name: test
      run: xvfb-run ninja -v -C builddir test
    - name: install
      run: sudo ninja -C builddir install
